apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockgametracker
spec:
  replicas: 3
  template:
    metadata:
      name: blockgametracker
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers: # Override Kubernetes DNS
          - 1.1.1.1
          - 1.0.0.1
          - 8.8.8.8
      containers:
        - name: app
          image: ghcr.io/clrxbl/blockgametracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: blockgametracker
  selector:
    matchLabels:
      app: blockgametracker