apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockgametracker
spec:
  template:
    spec:
      containers:
        - name: app
          image: blockgametracker
          imagePullPolicy: Always
          env:
            - name: CONFIG_FILE
              value: "config/servers.yaml"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels: {}
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: blockgametracker