apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configurations:
  - kustomizeconfig/servicemonitor-labels.yaml
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: blockgametracker
images:
  - name: blockgametracker
    newName: ghcr.io/clrxbl/blockgametracker
    newTag: latest
configMapGenerator:
  - name: blockgametracker
    files:
      - config/servers.yaml
    options:
      disableNameSuffixHash: true