apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blockgametracker
spec:
  selector:
    matchLabels: {}
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics